name: TF Apply

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docker/**"

env:
  TF_VERSION: 1.1.7
  AWS_REGION: us-west-2 
  AWS_AZ: us-west-2a

jobs:

  terraform-apply:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: "setup Terraform"
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -no-color -auto-approve \
        -var="aws_region=${{ env.AWS_REGION }}" \
        -var="availability_zone=${{ env.AWS_AZ }}"